//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheBoatClub.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheBoatClub.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;medlemmar&gt;
        ///&lt;medlem&gt;
        ///  &lt;medlemsnr&gt;0&lt;/medlemsnr&gt;
        ///  &lt;personnr&gt;781015&lt;/personnr&gt;
        ///  &lt;namn&gt;Pelle Svensson&lt;/namn&gt;
        ///  &lt;batar&gt;
        ///	&lt;bat&gt;
        ///		&lt;typ&gt;Motorbåt&lt;/typ&gt;
        ///		&lt;langd&gt;8 m&lt;/langd&gt;
        ///	&lt;/bat&gt;
        ///  &lt;/batar&gt;
        ///&lt;/medlem&gt;
        ///&lt;medlem&gt;
        ///  &lt;medlemsnr&gt;1&lt;/medlemsnr&gt;
        ///  &lt;personnr&gt;520410&lt;/personnr&gt;
        ///  &lt;namn&gt;Anna Nilsson&lt;/namn&gt;
        ///  &lt;batar&gt;
        ///	&lt;bat&gt;
        ///		&lt;typ&gt;Segelbåt&lt;/typ&gt;
        ///		&lt;langd&gt;5 m&lt;/langd&gt;
        ///	&lt;/bat&gt;
        ///	&lt;bat&gt;
        ///		&lt;typ&gt;Eka&lt;/typ&gt;
        ///		&lt;langd&gt;3 m&lt;/langd&gt;
        ///	&lt;/bat&gt;
        ///  &lt;/batar&gt;
        ///&lt;/medlem&gt;
        ///&lt;/medlemmar&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string data {
            get {
                return ResourceManager.GetString("data", resourceCulture);
            }
        }
    }
}
